//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_EXIT_INTERVIEW_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInformation
    {
        public int Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string HrId { get; set; }
        public string Hiredate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FullName { get; set; }
        public string Site { get; set; }
        public string SeparationDate { get; set; }
        public string HiringDate { get; set; }
        public string LineOfBusiness { get; set; }
    }
}
