//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_EXIT_INTERVIEW_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completion
    {
        public int Id { get; set; }
        public string Hrid { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
    }
}
