//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_EXIT_INTERVIEW_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VXI_EXIT_INTERVIEW_FINAL_PAYEntities : DbContext
    {
        public VXI_EXIT_INTERVIEW_FINAL_PAYEntities()
            : base("name=VXI_EXIT_INTERVIEW_FINAL_PAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountInformation> AccountInformation { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<Completion> Completion { get; set; }
        public virtual DbSet<EmailerDistro> EmailerDistro { get; set; }
        public virtual DbSet<OtherEmployeeDetails> OtherEmployeeDetails { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<RequestAttachments> RequestAttachments { get; set; }
        public virtual DbSet<SiteLocation> SiteLocation { get; set; }
        public virtual DbSet<SurveyCheckerOnline> SurveyCheckerOnline { get; set; }
        public virtual DbSet<SurveyInfo> SurveyInfo { get; set; }
        public virtual DbSet<UserAnswer> UserAnswer { get; set; }
    
        public virtual ObjectResult<usp_Report_Result> usp_Report(string startDate, string endDate, string site)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_Result>("usp_Report", startDateParameter, endDateParameter, siteParameter);
        }
    
        public virtual ObjectResult<usp_Report_bydate_Result> usp_Report_bydate(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_bydate_Result>("usp_Report_bydate", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<usp_Report_ById_Result> usp_Report_ById(string hrid)
        {
            var hridParameter = hrid != null ?
                new ObjectParameter("Hrid", hrid) :
                new ObjectParameter("Hrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_ById_Result>("usp_Report_ById", hridParameter);
        }
    
        public virtual ObjectResult<usp_Report_FinalPay_Result> usp_Report_FinalPay(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_FinalPay_Result>("usp_Report_FinalPay", startDateParameter, endDateParameter);
        }
    }
}
