//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_EXIT_INTERVIEW_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public System.Guid QuestionID { get; set; }
        public Nullable<System.Guid> SurveyID { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public string QuestionAnswer { get; set; }
        public string QuestionDescription { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> Createdby { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OtherAnswer { get; set; }
        public Nullable<bool> hasOther { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual SurveyInfo SurveyInfo { get; set; }
    }
}
