//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_EXIT_INTERVIEW_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAttachments
    {
        public int Id { get; set; }
        public string OriginalFileName { get; set; }
        public string SavedFileName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreateBy { get; set; }
    }
}
