//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXI_EXIT_INTERVIEW_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int Id { get; set; }
        public System.Guid UserAnswerID { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> AnswerID { get; set; }
        public Nullable<System.Guid> QuestionID { get; set; }
        public Nullable<System.Guid> SurveyID { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> Createdby { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OtherResponse { get; set; }
    
        public virtual Answer Answer { get; set; }
    }
}
